const kodam = [
    'Kanjeng Ratu Kidul',
    'Eyang Semar',
    'Wali Songo',
    'Noyo Genggong',
    'Dewa Neptunus',
    'Dewa Zeus',
    'Naga Hitam',
    'Barongsai',
    'Tuyul',
    'Pocong',
    'Harimau Cakar Baja',
    'Genderuwo',
    'Sundel Bolong',
    'Kepiting Kikir',
    'Buaya darat',
    'Gada, Kodam aja gada, apalagi doi, wkwk',
    'Nyai Roro Kidul',
    'Dewi Sri',
    'Hanoman',
    'Garuda',
    'Kyai Slamet',
    'Raden Wijaya',
    'Prabu Siliwangi',
    'Singa Perkasa',
    'Elang Emas',
    'Harimau Putih',
    'Naga Merah',
    'Macan Kumbang',
    'Bajing Loncat',
    'Buaya Hitam',
    'Rusa Baik Hati',
    'Ular Sanca',
    'Ikan Paus',
    'Gajah Perkasa',
    'Anjing Laut',
    'Beruang Madu',
    'Hiu Karang',
    'Gorilla Sakti',
    'Kucing Oren',
    'Burung Hantu',
    'Komodo Ganas',
    'Tikus Kantoran',
    'Laptop Sakti',
    'HP Gaib',
    'Motor Terbang',
    'Sepeda Ontel',
    'Kopi Gaib',
    'Cincin Sakti',
    'Peci Ajaib',
    'Sarung Sakti',
    'Baju Zirah',
    'Pedang Gaib',
    'Payung Terbang',
    'Celana Dalang',
    'Sepatu Roda',
    'Sapu Ajaib',
    'Batu Akik',
    'Gantungan Kunci Kodam',
    'Pensil Gaib',
    'Tas Ransel Gaib',
    'Sendal Jepit Sakti',
    'Bantal Gaib',
    'Kursi Gaib',
    'Asep Gentong',
    'Lumpur Lapindo',
    'Charger Laptop',
    'Charger Iphone',
    'Lautan Susu',
    'Asam Folat',
    'Mediatek T618',
    'Snapdragon P10',
    'Unisoc 665',
    'Sukaloli',
    'Speaker JBL',
    'Bodrex Migrain',
    'Teh Jumbo 3000',
    'Covid 19',
    'Local Pride',
    'Raja Fesnuk',
    'TWS gaming',
    'RTX 4090Ti',
    'Intel Celeron',
    'AMD Ryzen 5500u',
    'Korek Gas',
    'LPG 3KG',
    'OK GAS',
    'Paramex',
    'Ternak Lele',
    'Cacing Besar Alaska',
    'Cacing Tipes',
    'Marinasi Tempe',
    'Burung Kecengklak',
    'Keran Bocor',
    'Belut Listrik',
    'Kodok Dribble',
    'Singa Mewing',
    'Undur Undur Maju',
    'Seblak Dower',
    'Rice Cooker',
    'Bakwan Jagung',
    'Dodol Accident',
    'Daun Jeruk',
    'Tahu Gejrot',
    'Sigma',
    'Susu',
    'Sambal Bubuk',
    'Ayam Geprek',
    'Jagung',
    'Sayur Asem',
    'Gedung DPR',
    'Ayam RGB',
    'Maskot Mixue',
    'Infinix Note 30 Pro',
    'Nutri Sari Jeruk Peras',
    'Lele Mengeluh',
    'Naga Salto',
    'Laba Laba Sunda',
    'Taplak Meja',
    'Gagang Pintu',
    'Bubur Ayam',
    'Minyak Bumi',
    'Spion',
    'Kabel RJ45',
    'Spidol Permanen',
    'Es Batu',
    'Gojo Berdoa',
    'Gyat Level 100',
    'Gyat Belajar',
    'Anaconda',
    'Harimau Sumatra',
    'Batak',
    'Sitfose',
    'Incik Bin Kamis',
    'Es Krim Sandwich',
    'Cocolemon',
    'Tinta Squidward',
    'Kuda Dribble',
    'STB',
    'Tower 4G',
    'Wifi Warkop',
    'Kepiting Maju',
    'Ular Berkaki',
    '2RB 1GB',
    'Kuota SMS & Telepon',
    'Kuota Games Unilimited',
    'Bjorka',
    'Kominfo',
    'FB Lite',
    'Staples',
    'Pompa Angin 200 PSI',
    'Charger Fast Charging',
    'Esemka',
    'Mazda Miata',
    'Mio Mirza',
    'OPM',
    'Bank Mandiri',
    'Es Dawet',
    'Telur Dadar',
    'Gemoy',
    'Peliharaan Yahudi',
    'Orang Papua Asli',
    'Maniak Bola',
    'Botol Minum',
    'Rice Cooker',
    'Semen Tiga Roda',
    'Semangka',
    'Melon',
    'Sakatonik ABC',
    'Ekstrak Kulit Manggis',
    'Headset RGB',
    'Goku',
    'Dodge Charger',
    'Supra Bapak',
    'Pendukung Anies',
    'Godzilla',
    'XBOX 360',
    'Playstation 2 Fat',
    'Carl Johnson',
    'Big Smoke',
    'Number 7',
    'Betadine',
    'Terminal Kuningan',
    'Nokia 6600',
    'Speaker Bluetooth',
    'TWS',
    'Fanboi TWICE',
    'Klan Uciha',
    'Klux Klux Klan',
    'Anak Abah',
    'Laundry 5000/kg',
    'SoKlin Cuci Piring',
    'Deterjen',
    'Paracetamol 500mg',
    'Vitamin C 1000mg',
    'Kabel USB',
    'Kardus',
    'Kipas Angin',
    'Karbon Dioksida',
    'Nitrogen',
    'Hidrogen Meledak',
    'Ular Berlari',
    'Burung Tidak Berhantu',
    'Router Wifi',
    'Chipset',
    'Budak VOC',
    'Orang Hitam Legit',
    'Sweet Johnson',
    'Anomali Top Frag',
    'SCP-6959'
];

// Define the async handler function
let handler = async (m, { conn, text }) => {
    // Check if the text is provided
    if (!text) {
        return conn.reply(m.chat, 'Masukkan Namamu', m);
    }
    
    // Send loading message
    conn.reply(m.chat, 'Sedang meramal Kodam kamu🔮...', m);
    
    // Simulate a delay to show the loading message (e.g., 2 seconds)
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Select a random kodam from the array
    let khodam = kodam[Math.floor(Math.random() * kodam.length)];
    
    // Reply with the user's name and their kodam
    conn.reply(m.chat, `Nama Kamu: ${text}\nKodam Kamu: ${khodam}`, m);
};

// Define the help and tags for the command
handler.help = ['cekkodam'].map(v => v + ' <name>');
handler.tags = ['fun'];
handler.command = /^(cekkodam)$/i;

// Export the handler as the default export
export default handler;